server:
  port: 8080
  servlet:
    context-path: /deep
spring:
  profiles:
    active: ${spring.profiles.active}
  cache:
    type: redis
  application:
    name: deep-application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.ip}:${database.port}/zswblog?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&connectTimeout=30000&socketTimeout=60000&useSSL=false
    username: root
    password: 732668
  redis:
    host: ${redis.ip}
    port: ${redis.port}
    password: 732668
    database: 0
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: ${rabbit.ip}
    port: 5672
    username: root
    password: zsw158991626ZSW


# 服务信息，显示在/info页面
info:
  name: springboot-deep
  gourpId: com.sandman

elasticsearch:
  hostList: ${elasticsearch.ip}


# mybatis配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  #  mapper-locations: classpath:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sandman.entity
  typeEnumsPackage: com.sandman.constant
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断",NOT_EMPTY:"非空判断"
      insert-strategy: NOT_NULL
      select-strategy: NOT_NULL
      #驼峰下划线转换
      table-underline: true
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置及全局字段名称（下面3个配置）
  #      logic-delete-field: deleted
  #      logic-delete-value: 1
  #      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    #配置JdbcTypeForNull
    jdbc-type-for-null: NULL